server:
  port: 8021
spring:
  devtools:
    restart:
      enabled: true
  mail:
    username: 1462718182@qq.com  #\u4fee\u6539\u4e3a\u81ea\u5df1\u7684\u90ae\u7bb1
    password: bjfwqtyzytuphajb  #\u6388\u6743\u7801\uff08\u7b2c\u4e09\u6b65\u4e2d\u751f\u6210\u7684\u6388\u6743\u7801\uff09
    host: smtp.qq.com  #\u53d1\u9001\u90ae\u4ef6\u7684\u670d\u52a1\u4e3b\u673a
    properties:
      mail: 
        smtp: 
          ssl: 
            enable: true  #\u5f00\u542fssl\u5b89\u5168
  datasource:
    username: root 
    password: root  #\u4fee\u6539\u4e3a\u81ea\u5df1\u7684\u6570\u636e\u5e93\u5bc6\u7801
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai 

    
mybatis:
  # \u6307\u5b9a\u5168\u5c40\u914d\u7f6e\u6587\u4ef6\u4f4d\u7f6e
  config-location: classpath:mybatis/mybatis-config.xml
  # \u6307\u5b9asql\u6620\u5c04\u6587\u4ef6\u4f4d\u7f6e
  mapper-locations: classpath:mybatis/mapper/*.xml  
  
  
logging:
   level:
     com.ibm.springboot.controller.LoggingController: trace  #\u8bbe\u7f6e\u8f93\u51fa\u7ea7\u522b
#     com.ibm6.mapper: debug

#\u00a01.\u4e0d\u6307\u5b9a\u8def\u5f84\u65f6\u4f1a\u5728\u5f53\u524d\u9879\u76ee\u4e0b\u751f\u6210springboot.log\u65e5\u5fd7
#\u00a02.\u53ef\u4ee5\u6307\u5b9a\u5b8c\u6574\u7684\u8def\u5f84,\u5982\uff1aD:/springboot.log
   file: springboot.log
  
#\u00a0\u5728\u5f53\u524d\u78c1\u76d8\u7684\u6839\u8def\u5f84\u4e0b\u521b\u5efaspring\u6587\u4ef6\u5939\u548c\u91cc\u9762\u7684log\u6587\u4ef6\u5939;
#\u4f7f\u7528\u00a0spring.log\u00a0\u4f5c\u4e3a\u9ed8\u8ba4\u6587\u4ef6;
#\u5f53file\u548cpath\u540c\u65f6\u4f7f\u7528\u65f6,\u4ee5file\u4e3a\u51c6
#   path: /spring/log
   
#\u00a0\u00a0\u5728\u63a7\u5236\u53f0\u8f93\u51fa\u7684\u65e5\u5fd7\u7684\u683c\u5f0f   
   pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n'
#\u00a0\u6307\u5b9a\u6587\u4ef6\u4e2d\u65e5\u5fd7\u8f93\u51fa\u7684\u683c\u5f0f    
    file: '%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} === - %msg%n'
